name: dispatch-sim-evaluation-tools
on:
  pull_request:
    types: [labeled]

jobs:
  make_dispatch_event:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'execute-autoware-evaluator'
    steps:
      - name: trigger
        env:
          pull_request_info: ${{ toJSON(github.event.pull_request) }}
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/tier4/sim_evaluation_tools_test/dispatches" \
            -d '{"event_type":"pull_request_notification","client_payload":{"config":"autoware","pr":"${pull_request_info}" }}'
