name: sync_pull_request
on:
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  make_dispatch_event:
    runs-on: ubuntu-latest
    steps:
    - name: trigger
      run: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/HansRobo/test_github_workflow_project/dispatches \
          -d '{"event_type":"test","client_payload":{"pull_request_number":${{ github.event.pull_request.number }}}}'