name: sync_pull_request
on:
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  make_dispatch_event:
    runs-on: ubuntu-latest
    steps:
    - name: trigger
      run: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/HansRobo/test_github_workflow_project/dispatches \
          -d '{"event_type":"pull_request_notification", \
               "client_payload":{"branch_name": "${{ github.event.pull_request.head.ref }}", "pr_number": "${{ github.event.pull_request.number }}" }}'
